language: ruby
dist: bionic

rvm: 2.6.3

services:
  - redis

sudo: false

cache: bundler

bundler_args: --without development --jobs 3 --retry 3 --deployment

before_install: gem install bundler

script: bundle exec rspec spec

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec spec
    - stage: ":ship: it"
      script: make ship
